version: 0.0
os: linux
files:
  - source: /home/ubuntu/kiosk
    destination: /home/ubuntu/build
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 300
      runas: ubuntu
